# Generated by Django 5.1.4 on 2024-12-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('start_at', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('participationer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشارکت',
                'verbose_name_plural': 'مشارکت ها',
                'db_table': 'participations',
            },
        ),
    ]
